# Generated by Django 5.2.5 on 2025-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_rating',
            field=models.CharField(choices=[(0, 'ALL'), (7, '7세'), (12, '12세'), (15, '15세'), (19, '19세')], default=0, max_length=3),
        ),
    ]
