# Generated by Django 5.2.5 on 2025-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ALL'), (7, '7세'), (12, '12세'), (15, '15세'), (19, '19세')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=7, null=True),
        ),
    ]
